import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Home/Navbar";
import { Footer } from "@/components/Home/Footer";

const poppins = Poppins({
  subsets: ["latin"],

  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "My virtual Doctor(MVD)",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="width">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
